version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo apt install -y -q awscli
      - run: sudo npm install -g gulp && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: gulp bundle-prod
      - run: gulp test

      # deploy!
      - run: aws configure set default.s3.signature_version s3v4
      - run: aws configure set default.region ca-central-1
      - run: aws configure set preview.cloudfront true
      - run: aws configure set preview.create-invalidation true
      - run: aws s3 sync dist/prod/ s3://chris-and-sheena-dot-com/ --delete
      - run: aws cloudfront create-invalidation --distribution-id EAG77K766NM9Y --invalidation-batch file://.circleci/cf-invalidation.json
