/* eslint "no-console": 0 */

import _ from 'lodash';
import AWS from 'aws-sdk';
import Bluebird from 'bluebird';

const Lambda = new AWS.Lambda({ apiVersion: '2015-03-31', region: 'us-east-1' });
const S3 = new AWS.S3();

Bluebird.promisifyAll(S3);

function invoke(params) {
	return new Bluebird((resolve, reject) => {
		Lambda.invoke(params, (err, success) => {
			if (err) return reject(err);
			resolve(success);
		});
	});
}

if (!process.argv[2]) {
	console.error('You must include the bucket name as a command line argument. :(');
	process.exit(1);
}

const BUCKET_NAME = process.argv[2];

function listAllTheFiles(bucketName) {
	return new Bluebird((resolve, reject) => {
		var items = [];

		const handleResponse = data => {
			items = _.concat(
				items,
				_.filter(data.Contents, item => {
					// Remove anything that was generated by the transcoder.
					return item.StorageClass !== 'REDUCED_REDUNDANCY';
				}));

			if (!data.IsTruncated) {
				return resolve(items);
			}

			S3.listObjectsV2Async({
				Bucket: bucketName,
				MaxKeys: 1000,
				ContinuationToken: data.NextContinuationToken })
				.then(handleResponse)
				.catch(reject);
		};

		S3.listObjectsV2Async({ Bucket: bucketName, MaxKeys: 1000 })
			.then(handleResponse)
			.catch(reject);
	});
}

function runInvocations(items) {
	return new Bluebird((resolve, reject) => {
		var index = 1;

		const callback = value => {
			console.log('Finished', index, 'of', items.length, '-', value);

			if (index >= items.length) {
				return resolve();
			}

			invoke({
				FunctionName: 'makeThumbnail',
				InvocationType: 'RequestResponse',
				Payload: JSON.stringify({
					bucket: BUCKET_NAME,
					key: items[index++].Key
				})
			})
			.then(callback)
			.catch(reject);
		};

		if (!items || items.length === 0) {
			return resolve();
		}

		invoke({
				FunctionName: 'makeThumbnail',
				InvocationType: 'RequestResponse',
				Payload: JSON.stringify({
					bucket: BUCKET_NAME,
					key: items[0].Key
				})
			})
			.then(callback)
			.catch(reject);
	});
}

listAllTheFiles(BUCKET_NAME)
	.then(data => {
		return runInvocations(
			_.filter(data, item => {
				return /(\.jpg|\.jpeg|\.png)$/i.test(item.Key);
			})
		);
	})
	.then(items => {
		runInvocations(items);
	})
	.then(() => {
		console.log('Thumbnails have been generated.');
	})
	.catch(err => {
		console.error('Oh noes! ', err);
		process.exit(1);
	});
