import _ from 'lodash';
import AWS from 'aws-sdk';
import Bluebird from 'bluebird';
import getSlug from 'speakingurl';
import path from 'path';

const S3 = new AWS.S3();
Bluebird.promisifyAll(S3);

if (!process.argv[2]) {
	console.error('You must include the bucket name as a command line argument. :(');
	process.exit(1);
}

if (!process.argv[3]) {
	console.error('C\'mon man, you have to give a screen-friendly name for this collection. :(');
	process.exit(1);
}

const BUCKET_NAME = process.argv[2];
const FRIENDLY_NAME = process.argv[3];

function urlify(bucket, key, removeWhitespace) {
	return `https://s3.amazonaws.com/${bucket}/${key.replace(/ /g, removeWhitespace ? '' : '+')}`;
}

function listAllTheFiles(bucketName) {
	return new Bluebird((resolve, reject) => {
		var items = [];

		const handleResponse = data => {
			items = _.concat(
				items,
				_.filter(data.Contents, item => {
					// Remove anything that was generated by the transcoder.
					return item.StorageClass !== 'REDUCED_REDUNDANCY';
				}));

			if (!data.IsTruncated) {
				return resolve(items);
			}

			S3.listObjectsV2Async({
				Bucket: bucketName,
				MaxKeys: 1000,
				ContinuationToken: data.NextContinuationToken })
				.then(handleResponse)
				.catch(reject);
		};

		S3.listObjectsV2Async({ Bucket: bucketName, MaxKeys: 1000 })
			.then(handleResponse)
			.catch(reject);
	});
}

listAllTheFiles(BUCKET_NAME)
	.then(data => {
		const manifest = {
			Info: {
				Name: FRIENDLY_NAME,
				Bucket: BUCKET_NAME,
				Slugs: {}
			},
			Contents: {}
		};

		for (var i = 0; i < data.length; i++) {
			const parsed = path.parse(data[i].Key);
			const split = parsed.dir.split('/');

			var node = manifest;
			var slugNode = manifest.Info.Slugs;
			for (var j = 0; j < split.length; j++) {
				const slug = getSlug(split[j]);

				if (!node.Contents[split[j]]) {
					node.Contents[split[j]] = {
						Slug: slug,
						Contents: {}
					};
				}

				if (!slugNode[slug]) {
					slugNode[slug] = {
						_Key: split[j]
					}
				}

				node = node.Contents[split[j]];
				slugNode = slugNode[slug];
			}

			node.Contents[parsed.name] = {
				Key: data[i].Key,
				Url: urlify(BUCKET_NAME, data[i].Key),
				Slug: getSlug(parsed.name)
			};

			if (/(\.mp4|\.mov)$/i.test(parsed.ext)) {
				node.Contents[parsed.name].Type = 'video/mp4';
				node.Contents[parsed.name].ThumbnailUrl = urlify(
					BUCKET_NAME,
					`${parsed.dir}/${parsed.name}-00001.png`);
				node.Contents[parsed.name].HlsUrl = urlify(
					BUCKET_NAME,
					`${parsed.dir}/${parsed.name}-hls${parsed.ext}`);
				node.Contents[parsed.name].DashUrl = urlify(
					BUCKET_NAME,
					`${parsed.dir}/${parsed.name}-dash.mpd`,
					true);
			}

			else if (/(\.jpg||\.jpeg)$/i.test(parsed.ext)) {
				node.Contents[parsed.name].Type = 'image/jpeg';
			}

			else {
				throw 'Unknown type: ' + parsed.ext;
			}
		}

		console.log(`module.exports = ${JSON.stringify(manifest, null, 2)};`);
	})
	.catch(err => {
		console.error('Oh noes! Failed!!', err);
	});
